server:
  port: 8080

spring:
  application:
    name: video_store_exam
  datasource:
    url: jdbc:mysql://${MYSQL_HOSTNAME}:${MYSQL_PORT}/${MYSQL_DATABASE_NAME}?ssl-mode=REQUIRED
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
     ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
logging:
  level:
    it.cgmconsulting.capriello: info
    org.hibernate.orm.jdbc.bind: trace
    org.springframework: info

spring-doc:
  swagger-ui:
    # in produzione dobbiamo mettere false
    enabled: true
    # hostname:port/swagger-ui.html => localhost:8080/swagger-ui.html
    path: /swagger-ui.html